// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type AuthResponse struct {
	AuthToken *AuthToken `json:"authToken"`
	User      *User      `json:"user"`
}

type AuthToken struct {
	Token     string    `json:"token"`
	ExpiredAt time.Time `json:"expiredAt"`
}

type NewReviewInput struct {
	Score  int    `json:"score"`
	Text   string `json:"text"`
	WineID int    `json:"wineID"`
	UserID int    `json:"UserID"`
}

type NewWineInput struct {
	Name     string `json:"name"`
	ShortDes string `json:"shortDes"`
	WineryID int    `json:"wineryID"`
}

type NewWineryInput struct {
	Name     string `json:"name"`
	Location string `json:"location"`
	Stars    int    `json:"stars"`
}

type RegisterInput struct {
	Username        string `json:"username"`
	Password        string `json:"password"`
	Confirmpassword string `json:"confirmpassword"`
	Email           string `json:"email"`
	FirstName       string `json:"firstName"`
	LastName        string `json:"lastName"`
}

type UpdateReviewInput struct {
	Score int    `json:"score"`
	Text  string `json:"text"`
}

type UpdateWineInput struct {
	Name     string `json:"name"`
	ShortDes string `json:"shortDes"`
}

type UpdateWineryInput struct {
	Name     string `json:"name"`
	Location string `json:"location"`
	Stars    *int   `json:"stars"`
}

type WineFilter struct {
	Name *string `json:"name"`
}
