// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewReview struct {
	ID    string `json:"id"`
	Score int    `json:"score"`
	Text  string `json:"text"`
}

type NewUser struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Email    string `json:"email"`
}

type NewWine struct {
	Name     string `json:"name"`
	ShortDes string `json:"shortDes"`
}

type NewWinery struct {
	Name     string `json:"name"`
	Location string `json:"location"`
	Stars    *int   `json:"stars"`
}
